/* ReqA */
SELECT IDCHANTIER,DATEDEBUT,BUDGET
FROM CHANTIER;

/* ReqB */

SELECT NOM
FROM ARCHITECTE 
WHERE ARCHITECTE.IDARCHI=3;

/* ReqC */

SELECT NOM,PRENOM
FROM CLIENT
WHERE ADRESSE='VALENCIENNES';

/* ReqD */

SELECT INTITULE 
FROM PROJET
WHERE PROJET.MONTANT>30000

/* ReqE */

SELECT CHANTIER.BUDGET
FROM CHANTIER,ARTISAN
WHERE ARTISAN.NOM='DUPONT'
AND ARTISAN.IDARTISAN=CHANTIER.IDARTISAN;


/* ReqF */

SELECT INTITULE
FROM PROJET,ARCHITECTE
WHERE ARCHITECTE.FONCTION='chef déquipe'
AND ARCHITECTE.IDARCHI=PROJET.IDARCHI;

/* ReqG */

SELECT NOM
FROM ARTISAN,CHANTIER
WHERE ARTISAN.IDARTISAN=CHANTIER.IDARTISAN
AND CHANTIER.IDCHANTIER=2;


/* ReqH */

SELECT NOM
FROM ARTISAN 
WHERE ARTISAN.NOM NOT IN (
                        SELECT NOM
                        FROM ARTISAN,CHANTIER
                        WHERE ARTISAN.IDARTISAN=CHANTIER.IDARTISAN
                        AND CHANTIER.IDCHANTIER=2
);

/* ReqI */

SELECT ARTISAN.NOM
FROM ARTISAN,CLIENT,CHANTIER,PROJET
WHERE CLIENT.NOM='DUPONT'
AND PROJET.IDCLIENT=CLIENT.IDCLIENT
AND ARTISAN.IDARTISAN=CHANTIER.IDARTISAN
AND PROJET.IDPROJET=CHANTIER.IDPROJET;

/* ReqJ */

SELECT SUM(BUDGET)
FROM PROJET,CHANTIER,CLIENT
WHERE CLIENT.NOM='DUPONT'
AND PROJET.IDCLIENT=CLIENT.IDCLIENT
AND PROJET.IDPROJET=CHANTIER.IDPROJET;